# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



#mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.179.0/vsts-agent-linux-x64-2.179.0.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "$(command -v systemctl)" ]; then ./config.sh --deploymentgroup --deploymentgroupname "OIDC - Testing" --acceptteeeula --agent $HOSTNAME --url https://cousant.visualstudio.com/ --work _work --projectname 'OIDC' --runasservice; ./svc.sh install; ./svc.sh start; else ./config.sh --deploymentgroup --deploymentgroupname "OIDC - Testing" --acceptteeeula --agent $HOSTNAME --url https://cousant.visualstudio.com/ --work _work --projectname 'OIDC'; ./run.sh; fi

#scp -i /users/mac/.ssh/oidc/id_rsa -r vsts-agent-linux-arm64-2.181.0.tar.gz root@159.89.22.14:/vsts-agent-linux-arm64-2.181.0.tar.gz